version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dev_nodejs_backend
    ports:
      - "3001:3000"
    working_dir: /app/
    command: ["npm", "start"]
    restart: unless-stopped
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_PORT: ${NEO4J_PORT}
      
volumes:
  shared_code:
